[package]
name = "forrustts"
version = "0.1.0"
authors = ["molpopgen <krthornt@uci.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
paste = "1.0.4"
GSL = "2.0.1"
tskit_rust = { git = "https://github.com/molpopgen/tskit_rust", branch = "main" }
