[package]
name = "forrustts"
version = "0.1.0"
authors = ["molpopgen <krthornt@uci.edu>"]
edition = "2018"
description = "Tools for forward simulation with tree sequence recording"
license-file = "LICENSE"
homepage = "https://github.com/molpopgen/forrustts"
repository = "https://github.com/molpopgen/forrustts"
keywords = ["simulation", "tree_sequences", "tskit", "population_genetics"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
thiserror = "1.0"
GSL = "2.0.1"
tskit_rust = "0.1.0"
